name: atlassian_apis
description: A client to access the Atlassian REST APIs (Jira Cloud platform, Service Desk, Confluence)
version: 0.8.0
homepage: https://github.com/xvrh/atlassian_apis

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.0
  path: ^1.8.0

dev_dependencies:
  analyzer:
  build_runner:
  collection:
  dart_style:
  json_annotation:
  json_serializable:
  lints:
  pub_semver:
  test:
  yaml: