name: atlassian_apis
description: A client to access the Atlassian REST APIs (Jira Cloud platform, Service Desk, Confluence)
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  path:

dev_dependencies:
  build_runner:
  dart_style:
  json_annotation:
  json_serializable:
  pedantic:
  test:
